version: '3'
services:
    compsoc-sso-demo:
        image: compsoc-sso-demo
        environment:
        - "FLASK_PREFERRED_URL_SCHEME=https"
        - "OAUTHLIB_RELAX_TOKEN_SCOPE=1"
        ports:
        - "8010:5000"
        volumes:
        - "./instance/:/app/instance/"
